config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "series#index"
  resources :series
  post "/filter_series", to: "series#filter_series"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :serie, touch: true

  validates :number, uniqueness: true
  validates :name, uniqueness: true
end

app/models/serie.rb
class Serie < ApplicationRecord
  belongs_to :prequel, class_name: "Serie", optional: true, dependent: :destroy
  belongs_to :sequel, class_name: "Serie", optional: true
  belongs_to :serie_type
  belongs_to :state

  has_many :episodes, dependent: :destroy
  accepts_nested_attributes_for :episodes, allow_destroy: true

  mount_uploader :cover_page_image, CoverPageImageUploader

  validates :prequel, uniqueness: true, allow_nil: true
  validates :sequel, uniqueness: true, allow_nil: true
  after_validation :link_prequel, if: -> { self.prequel_id.present? && self.prequel_id_changed? }
  after_validation :link_sequel, if: -> { self.sequel_id.present? && self.sequel_id_changed? }
  after_validation :unlink_prequel, if: -> { self.prequel_id.nil? && self.prequel_id_changed? }
  after_validation :unlink_sequel, if: -> { self.sequel_id.nil? && self.sequel_id_changed? }

  before_destroy :unlink_prequel, if: -> { self.prequel.present? }
  before_destroy :unlink_sequel, if: -> { self.sequel.present? }

  def link_prequel
    errors.add :prequel, message: "y sequela no pueden ser iguales." if self.prequel_id == self.sequel_id
    errors.add :prequel, message: "no puede ser la misma serie" if self.prequel_id == self.id
    errors.add :prequel, message: "ya tiene sequela" if self.prequel&.sequel_id&.present?

    serie_prequel = self.prequel
    serie_prequel.sequel = self
    serie_prequel.save(validate: false)
  end

  def link_sequel
    errors.add :sequel, message: "y sequela no pueden ser iguales." if self.prequel_id == self.sequel_id
    errors.add :sequel, message: "ya tiene prequela" if self.sequel&.prequel_id&.present?
    errors.add :sequel, message: "no puede ser la misma serie" if self.sequel_id == self.id

    serie_sequel = self.sequel
    serie_sequel.prequel = self
    serie_sequel.save(validate: false)
  end

  def unlink_prequel
    serie_prequel = Serie.find_by_id(self.prequel_id_was)
    serie_prequel.sequel = nil
    serie_prequel.save(validate: false)
  end

  def unlink_sequel
    serie_sequel = Serie.find_by_id(self.sequel_id_was)
    serie_sequel.prequel = nil
    serie_sequel.save(validate: false)
  end

end

app/models/serie_type.rb
class SerieType < ApplicationRecord
  SERIE = 1
  MOVIE = 2
  OVA = 3
  ESPECIAL = 4

  has_many :series
end

app/models/state.rb
class State < ApplicationRecord
  CONMING_SONG = 1
  CURRENTLY_AIRING = 2
  FINISHED_AIRING = 3

  has_many :series
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_action :set_serie, only: [:show, :edit, :update, :destroy]
  before_action :set_related, only: [:create, :update]

  # GET /series
  # GET /series.json
  def index
    if params[:q].present?
      params[:q][:name_start] = "" if params[:q][:name_start] == "0"
      params[:q][:state_id_eq] = "" if params[:q][:state_id_eq] == "0"
      params[:q][:serie_type_id_eq] = "" if params[:q][:serie_type_id_eq] == "0"
    end

    @q = Serie.ransack(params[:q])
    @series = @q.result(distinct: true)
  end

  # GET /series/1
  # GET /series/1.json
  def show
  end

  # GET /series/new
  def new
    @serie = Serie.new
  end

  # GET /series/1/edit
  def edit
  end

  # POST /series
  # POST /series.json
  def create
    @serie = Serie.new(serie_params)

    respond_to do |format|
      if @serie.save
        format.html { redirect_to @serie, notice: 'Serie was successfully created.' }
        format.json { render :show, status: :created, location: @serie }
      else
        format.html { render :new }
        format.json { render json: @serie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /series/1
  # PATCH/PUT /series/1.json
  def update
    respond_to do |format|
      if @serie.update(serie_params)
        format.html { redirect_to @serie, notice: 'Serie was successfully updated.' }
        format.json { render :show, status: :ok, location: @serie }
      else
        format.html { render :edit }
        format.json { render json: @serie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /series/1
  # DELETE /series/1.json
  def destroy
    @serie.destroy
    respond_to do |format|
      format.html { redirect_to series_url, notice: 'Serie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def filter_series
    series = Serie.filter_index(params[:selectWithLetter],
                                params[:selectWithType],
                                params[:selectWithState])
    render(json: series)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_serie
      @serie = Serie.find(params[:id])
    end

    def set_related
      params[:serie][:prequel_id] = nil if params[:serie][:prequel_id] == "0"
      params[:serie][:sequel_id] = nil if params[:serie][:sequel_id] == "0"
    end

    # Only allow a list of trusted parameters through.
    def serie_params
      params.require(:serie)
        .permit(:selectWithLetter, :selectWithType, :selectWithType, :name, :cover_page, :prequel_id, :sequel_id,
                :cover_page_image, episodes_attributes: [:id, :number, :duration, :name, :aired, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Series</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- CDN Font Awesome -->
    <script src="https://kit.fontawesome.com/65874f9339.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/series/_form.html.erb
<%
  page_name ||= ""

  image_name = "Choose Image"
  image_url = ""

  if @serie.cover_page_image.present?
    image_name = @serie.cover_page_image_identifier
    image_url = @serie.cover_page_image.url
  end
%>

<% if serie.errors.any? %>
  <div class="notification is-danger is-light">
    <button class="delete"></button>
    <div id="error_explanation">
      <h2 class="subtitle"><%= pluralize(serie.errors.count, "error") %> prohibited this serie from being saved:</h2>
      <ul>
        <% serie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

<div class="container">
  <%= form_with(model: serie) do |form| %>
    <div class="container">
      <div class="columns">
        <div class="column">
          <div class="columns">
            <div class="column">
              <%= image_tag image_url, height: "352", width: "250", class: "image_preview" %>
            </div>

            <div class="column is-flex is-align-items-flex-end">
              <div class="file is-primary">
                <label class="file-label">
                  <%= form.file_field :cover_page_image, class: "file-input" %>
                  <span class="file-cta">
                    <span class="file-icon">
                      <i class="fas fa-image"></i>
                    </span>
                    <span class="file-label">
                      <%= image_name %>
                    </span>
                  </span>
                </label>
              </div>
            </div>
          </div>

          <div class="field">
            <div class="control">
              <%= form.label :cover_page %>
              <%= form.text_field :cover_page, class: "input" %>
            </div>
          </div>

          <div class="field">
            <div class="control">
              <%= form.label :name %>
              <%= form.text_field :name, class: "input is-focused" %>
            </div>
          </div>

          <div class="field">
            <div class="control">
              <%= form.label :synopsis %>
              <%= form.text_area :synopsis, class: "textarea"%>
            </div>
          </div>
        </div>
        <div class="column">
          <div class="container">
            <div class="columns">
              <div class="column">
                <div class="field">
                  <div class="control">
                    <%= form.label :quantity_episodes %>
                    <%= form.number_field :quantity_episodes, class: "input" %>
                  </div>
                </div>

                <div class="field">
                  <div class="control">
                    <%= form.label :serie_type_id %>
                    <div class="select select--full_width">
                      <%= form.select :serie_type_id,
                                      ApplicationPresenter.get_all_serie_types("Select Serie Type"),
                                      {}, {class: "select--full_width"} %>
                    </div>
                  </div>
                </div>
              </div>
              <div class="column">
                <div class="field">
                  <div class="control">
                    <%= form.label :aired %>
                    <%= form.date_field :aired, class: "input" %>
                  </div>
                </div>
                <div class="field">
                  <div class="control">
                    <%= form.label :state_id %>
                    <div class="select select--full_width">
                      <%= form.select :state_id,
                                      ApplicationPresenter.get_all_serie_states("Select Serie State"),
                                      {}, {class: "select--full_width"} %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="container">
            <div class="columns">
              <div class="column">
                <div class="field">
                  <div class="control">
                    <%= form.label :prequel_id %>
                    <div class="select select--full_width">
                      <%= form.select :prequel_id,
                                      ApplicationPresenter.get_all_series_whithout_one(@serie, "Prequel"),
                                      {}, {class: "select--full_width"} %>
                    </div>
                  </div>
                </div>
                <div class="field">
                  <div class="control">
                    <%= form.label :sequel_id %>
                    <div class="select select--full_width">
                      <%= form.select :sequel_id,
                                      ApplicationPresenter.get_all_series_whithout_one(@serie, "Sequel"),
                                      {}, {class: "select--full_width"} %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <%# TODO: hacer que esta tabla sea responsive
      # * Se podria utilizar div simulando la tabla con la clase columns, para simular la tabla
    %>

    <div>
      <h2>Episodes</h2>
      <table class="table is-fullwidth">
        <thead>
          <tr>
            <th>Number</th>
            <th>Aired</th>
            <th>Name</th>
            <th>Duration</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <%= form.fields_for :episodes do |detail_form| %>
            <tr>
              <td>
                <div class="field">
                  <div class="control">
                    <%= detail_form.number_field :number, class: "input" %>
                  </div>
                </div>
              </td>
              <td>
                <div class="field">
                  <div class="control">
                    <%= detail_form.time_field :duration, class: "input" %>
                  </div>
                </div>
              </td>
              <td>
                <div class="field">
                  <div class="control">
                    <%= detail_form.text_field :name, class: "input" %>
                  </div>
                </div>
              </td>
              <td>
                <div class="field">
                  <div class="control">
                    <%= detail_form.date_field :aired, class: "input" %>
                  </div>
                </div>
              </td>
              <td>
                <div class="delete_container">
                  <%= detail_form.check_box :_destroy, class: "delete_container__btn" %>
                  <span class="delete"></span>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= render "components/add_has_many_btn", id: "add_has_many_serie" %>
    </div>
      <%= render "components/form_submit", page_name: page_name, form: form %>
  <% end %>
</div>

<%= javascript_pack_tag 'has_many.js' %>
<%= javascript_pack_tag 'serie.js' %>

app/views/series/edit.html.erb
<%# I need to repair this bug  %>
<%#= render 'components/navbar'%>

<h1 class="container title is-3 has-text-centered">Editing Serie</h1>

<%= render 'form', serie: @serie, page_name: "Update Serie" %>

app/views/series/index.html.erb
<div class="container is-fluid">
  <%# I need to repair this bug  %>
  <%#= render 'components/navbar', is_index: true %>

  <div class="columns is-multiline" id="series_container">
    <% @series.each do |serie| %>
      <div class="column is-one-fifth">
        <div class="card">
          <header class="card-header">
            <p class="card-header-title"><%= serie.name %></p>
          </header>
          <div class="card-image">
            <img src=<%= serie.cover_page %> style="width: 100%; height: 350px;">
          </div>
          <footer class="card-footer">
            <span class="card-footer-item"><%= link_to 'Show', serie %></span>
            <span class="card-footer-item"><%= link_to 'Edit', edit_series_path(serie) %></span>
            <span class="card-footer-item"><%= link_to 'Destroy', serie, method: :delete, data: { confirm: 'Are you sure?' } %></span>
          </footer>
        </div>
      </div>
    <% end %>
  </div>
</div>

<br>

<%= link_to 'New Serie', new_series_path %>
<%= javascript_pack_tag 'index.js' %>

app/views/series/new.html.erb
<%# I need to repair this bug  %>
<%#= render 'components/navbar'%>

<h1 class="container title is-3 has-text-centered">New Serie</h1>

<%= render 'form', serie: @serie, page_name: "Add Serie" %>

app/views/series/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card">
  <div class="card-head">
    <h3 class="title"> <%= @serie.name %> </h3>
  </div>

  <div class="card-body">
    <img src="<%= @serie.cover_page %>">
  </div>
</div>

<h2> Related </h2>
<div class="card-container">
  <% unless @serie.prequel.nil? %>
    <p> Prequel </p>
    <div class="card">
      <div class="card-head">
        <h3 class="title"> <%= @serie.prequel.name %> </h3>
      </div>

      <div class="card-body">
        <img src="<%= @serie.prequel.cover_page %>">
      </div>
    </div>
  <% end %>

  <% unless @serie.sequel.nil? %>
    <p> Sequel </p>
    <div class="card">
      <div class="card-head">
        <h3 class="title"> <%= @serie.sequel.name %> </h3>
      </div>

      <div class="card-body">
        <img src="<%= @serie.sequel.cover_page %>">
      </div>
    </div>
  <% end %>
</div>

<div>
  <h2>Episodes</h2>
  <table>
    <thead>
      <tr>
        <th>Number</th>
        <th>Name</th>
        <th>Aired</th>
        <th>Duration</th>
      </tr>
    </thead>
    <tbody>
      <% @serie.episodes.each do |episode| %>
      <tr>
        <td><%= episode.number %></td>
        <td><%= episode.name %></td>
        <td><%= episode.aired %></td>
        <td><%= episode.duration.to_s(:time) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to 'Edit', edit_series_path(@serie) %> |
<%= link_to 'Back', series_path %>